### ISSUE TITLE
Opening folders from the Go To Class window opens Method editor

### ISSUE THREAD

**Issue by Frogli** [suransys/go-to-class#2]
I just register this issue, so that it is known. Maybe I will fix it myself if needed.

I am not sure if this is by design, but it seemed strange to me that one I opened a folder from the mentioned window I got a method editor window. I would expect the Studio browser with the choosen folder opened. Although I am sure if this even possible. Maybe the folders sould be filtered from the search results.

**Comment by barkingfoodog** [comment]
I've removed the folders from the search results. I agree it doesn't make sense to include these since Omnis doesn't do anything when attempting to modify a folder.
