### ISSUE TITLE
Not all classes appear in the go-to-class window

### ISSUE THREAD

**Issue by Frogli** [suransys/go-to-class#5]
I noticed that not all classes can be found when you search for them in the go-to-class window. I tracked it back to the method wdGoToClass.$_buildClassList on line 1 where the list of classes is build. For test I insert below a line with directly point to a library.
```
Do $libs.MyLib.$classes.$makelist() Returns MyClasses
```
But this gives the same result. It is not just one type of classes (menus, windows, etc). Some menus can be found other can not. Then I create a new library and pasted a menu classes which could not be found in a library in this new library and also in this new library the menu class can not be found. Now if I create a new class (menu, window, or whatsoever) the class can be found. The strange thing is also that the Startup_Task also can not be found in this new library but can be found in my original library. 
Last thing I tested is copying a classes which could be found in my original library and pasted this in the new library. And this classes can be found in the new library.

I am puzzled and wondering why is $makelist leaving out some classes? Do you have any clue @barkingfoodog ? At this moment is seems more like an Omnis thing then something related to this project.

Thanks for looking into this.

Grtz

**Comment by barkingfoodog** [comment]
I suspect this is because some classes are set to `$external` and others aren't. I've changed the library's `$ignoreexternal` to `kTrue` so it ignores this property. Give this a try and see how it works.

**Comment by Frogli** [comment]
It has indeed something to do with $external, but the $ignoreexternal does not work for me. It does work if I set the $external to ```kTrue``` for the 'lost' classes, save the class in the Studio Browser and reopen the go-to-class window.

**Comment by Frogli** [comment]
Hold the phone... It does work. I thought you meant the $ignoreexternal for the production library, but you actually made a fix in the go-to-class library. My Apologies for the confusion. Btw the Omnis Library has the property $ignoreexternal still on kFalse. At least that was in my Omnis Studio when I downloaded the lbs from the repository and loaded it in Omnis Studio.

Btw did you encountered this problem before. I never would have thought the $external property would be the cause.

**Comment by barkingfoodog** [comment]
I double-checked the lbs and re-pushed it to github. `$ignoreexternal` should be set.

Yes, I've worked with the `$external` and `$ignoreexternal` properties before, mostly with our in-house VCS and OmnisTAP. This go-to-class project is extracted from our VCS which has `$ignoreexternal` set. It looks like I forgot to set it on the new library.

**Comment by Frogli** [comment]
ah right, yeah that was the thing I miss yet checking out classes from the VCS with shortcuts. But I am not sure I want to go to that effort since we will be looking in to switching to Git soon. Just downloaded the library again and loaded it in Omnis 8.1.5 and still the ```$ignoreexternal``` is kFalse. It is weird, not sure what's going on here...

Anyways thank you for helping out again!
